### ISSUE TITLE
Uploading metadata file fails during creating a new run

### ISSUE THREAD

**Issue by njmarine** [ohtap/subcorpora-tool#40]
<img width="898" alt="image" src="https://user-images.githubusercontent.com/50436011/69371870-86b53f00-0c55-11ea-826e-c85c86896f09.png">

It doesn't seem like I can upload a new metadata file. After selecting the file and clicking the UPLOAD button, the bar below turns from gray to blue. However, there is not output in the terminal to show that anything has been uploaded. And the NEXT button below never becomes active and we are not able to move on to the next step of creating a run.

**Comment by hsun083** [comment]
Issue: never set `isButtonDisabled` to false after metadata upload. Reset the state after successful upload and added logging in the console. Make sure to run `npm run build` after pulling the latest :)
