### ISSUE TITLE
Collections not being added to a new run

### ISSUE THREAD

**Issue by pjames27** [ohtap/subcorpora-tool#41]
When attempting to add a collection during creation of a new run, the new collection is logged to console as: "Current run collections updated to ", with no collection following.
Then, the collections array in runData is logged as: [ undefined ]
Ultimately, the script crashes with a "TypeError: NoneType is not subscriptable" error.

**Comment by hsun083** [comment]
Issue was that `SelectCollections.js` was trying to read the ID from the field `id` from the value, which wasn't set in `index.js`. Instead, it now just takes the key as the `id`.

**Comment by hsun083** [comment]
(Debugged this by logging out `collections` whenever the `updateSelection` function was called--you could see that the collections had IDs of `undefined`.)
